const List<String> kItems = [
  'jazz',
  'classical',
  'Rock',
  'Techno',
  'Trance',
  'Metal',
  'Folk',
  'Pop',
  'Hip Hop',
  'Black Metal',
  'Bass',
  'Soul Music',
  'Country Music',
  'Blues',
  'Electronic',
  'Punk Rock',
  'Disco',
  'Pop Rock',
  'Indie Rock',
  'Orchestra',
  'Ambient Music',
  'World Music',
  'Opera',
  'Contemporary',
  'Drum & Bass',
  'Experimental',
  'Death Metal',
  'Synth Pop',
  'Trap',
  'Breakbeat',
  'Dutch Rock',
  'Frenchcore',
  'Gabber',
  'Indorock',
  'Jordaanlied',
  'Levenslied',
  'Nederpop',
  'Palingsound',
  'Ultra'
];
